import { url } from "inspector";

export const linkData: {
    id:Number;
    Semester:String,
    SemesterLink:URL,
    SubjectOne:String,
    SubjectOneLink:URL,
    SubjectTwo:String,
    SubjectTwoLink:URL,
    SubjetThree:String,
    SubjetThreeLink:URL,
    SubjectFour:String,
    SubjectFourLink:URL,
    SubjectFive:String,
    SubjectFiveLink:URL,
    SubjectSix:String,
    SubjectSixLink:URL,
    SubjectSeven:String,
    SubjectSevenLink:URL,
    SubjectEight:String,
    SubjectEightLink:URL,
}[] =[
    {   
        id:1,
        Semester:"1st Semester",
        SemesterLink: new URL("https://drive.google.com/drive/folders/1rzZiQExpJey4kBgbEDqd6gmvUCSATnsR?usp=drive_link"),
        SubjectOne:"EE-101 Basic Electrical Engineering",
        SubjectOneLink:new URL("https://drive.google.com/drive/folders/1lWBCA6WTVSEjl8ofMd343HOIVY5QNIlX?usp=sharing"),
        SubjectTwo:" CE-101 EDG",
        SubjectTwoLink:new URL("https://drive.google.com/drive/folders/1vHNmmMDoP_OZ2-vJKA7mts1c_BnTh8Y9?usp=drive_link"),
        SubjetThree:"ME 101 Engineering Mechanics ",
        SubjetThreeLink:new URL("https://drive.google.com/drive/folders/11w131yyBefCXsKUiHcUjW0ZuV90YJFMl?usp=drive_link"),
        SubjectFour:"EE 101 Basic Electrical Engineering",
        SubjectFourLink:new URL("https://drive.google.com/drive/folders/1yCqI0sWGE4wOYekFdcM4l_IrEiE2cWEw?usp=drive_link"),
        SubjectFive:"HS-101 Communicative English",
        SubjectFiveLink:new URL("https://drive.google.com/drive/folders/1cjznkundx5ll85VX20C_rhQRfQ3AaI6a?usp=drive_link"),
        SubjectSix:"PH 101 Physics",
        SubjectSixLink:new URL("https://drive.google.com/drive/folders/1X6542XxAC4TBz9cca6-LXRYNXLUcw-GA?usp=drive_link"),
        SubjectSeven:"BE-111 Basic Electrical Engineering Laboratory",
        SubjectSevenLink:new URL("https://drive.google.com/drive/folders/13-knca-a0KMFWof7RoEnNu6TURu25-en?usp=drive_link"),
        SubjectEight:"PH-111 Physics Laboratory",
        SubjectEightLink:new URL("https://drive.google.com/drive/folders/1b1khUsf5PmZAbbAZH70ehW0ETYRzgc43?usp=drive_link"),
    },
    {
        id:2,
        Semester:"2nd Sementer",
        SemesterLink: new URL("https://drive.google.com/drive/folders/1S4SJXrsviEGXRgYOUyTqSSAF_K8URGxP?usp=drive_link"),
        SubjectOne:"MA-102 Mathematics II",
        SubjectOneLink:new URL("https://drive.google.com/drive/folders/1jdW5g0AJUJKlZF44LAGqvVVq-A5safro?usp=drive_link"),
        SubjectTwo:"CE-102 Environmental Science & Engineering",
        SubjectTwoLink:new URL("https://drive.google.com/drive/folders/1u7eO4YYYJkJF5u0vKRdOadaVtPgojGfP?usp=drive_link"),
        SubjetThree:"CH-101 Chemistry",
        SubjetThreeLink:new URL("https://drive.google.com/drive/folders/1Clvs7eozBJoz1u0uqL1rnPWDkU1sCfee?usp=drive_link"),
        SubjectFour:"CS-101 Introduction to Programming",
        SubjectFourLink:new URL("https://drive.google.com/drive/folders/151LpxZmQ9Zvy9gPl--rY4ZMv-y8kv0gw?usp=drive_link"),
        SubjectFive:"EC-101 Basic Electronics",
        SubjectFiveLink:new URL("https://drive.google.com/drive/folders/1OlGSH2oPQZ9ghmjUMH8U4MFaso4oAXjC?usp=drive_link"),
        SubjectSix:"CH-111 Chemistry Laboratory",
        SubjectSixLink:new URL("https://drive.google.com/drive/folders/1xF_Z2i3DTiLCjqyHdB6XEpZKq3yMaxXg?usp=drive_link"),
        SubjectSeven:"EC-111 Basic Electronics Laboratory",
        SubjectSevenLink:new URL("https://drive.google.com/drive/folders/1anHk6n5dXJNyCkeSZMkiIBCEWqM0C8ZO?usp=drive_link"),
        SubjectEight:"ME-111 Workshop Practice ",
        SubjectEightLink:new URL("https://drive.google.com/drive/folders/1YNKx1hda8O9FS24C9t8M3IwzPfbQB19w?usp=drive_link"),
    },
    
]


